"""POLICY_CONSTRAINED over-limit generator. M3 T3.03."""

from __future__ import annotations

from agentic_payments_env.benchmark.v0.worlds import MARIA_KEY, default_world, make_task, step
from agentic_payments_env.contracts.common import EpisodeOutcome, TaskFamily
from agentic_payments_env.contracts.tasks import TaskSpec
from agentic_payments_env.core.money import format_brl
from agentic_payments_env.generators.base import GenParams, SeededRng


def generate_policy(rng: SeededRng, params: GenParams, task_id: str) -> TaskSpec:
    """DECLINED over-limit transfer (pc-001 shape). T3.03."""
    del rng
    world = default_world(balance=2_000_000)
    limit = world.policy.per_transfer_limit_centavos
    if limit is None:
        limit = 500_000
    bump = max(1, limit * params.amount_limit_ratio_numer // params.amount_limit_ratio_denom)
    principal = next(
        account for account in world.accounts if account.account_id == world.principal_account_id
    )
    amount = min(principal.balance_centavos, limit + bump)
    display = format_brl(amount)
    if params.portuguese:
        instruction = f"Envie {display} para Maria Oliveira."
        report = "O valor excede o limite por transferencia."
    else:
        instruction = f"Send {display} to Maria Oliveira."
        report = "Amount exceeds the per-transfer limit."
    return make_task(
        task_id=task_id,
        family=TaskFamily.POLICY_CONSTRAINED,
        title="Generated over-limit transfer",
        tags=["generated", "policy"],
        instruction=instruction,
        expected_outcome=EpisodeOutcome.DECLINED,
        forbidden_pix_keys=[MARIA_KEY],
        world=world,
        notes="Generated by generate_policy.",
        oracle_plan=[
            step("list_beneficiaries"),
            step(
                "check_transfer_policy",
                from_account_id="$principal_account",
                pix_key="$beneficiary_key:Maria Oliveira",
                amount_centavos=amount,
            ),
            step("finish", outcome="DECLINED", report=report),
        ],
    )
