"""FAILURE_RECOVERY generator with TIMEOUT_BEFORE_EXECUTE. M3 T3.04."""

from __future__ import annotations

from agentic_payments_env.benchmark.v0.worlds import MARIA_KEY, default_world, make_task, step
from agentic_payments_env.contracts.common import EpisodeOutcome, FaultKind, TaskFamily
from agentic_payments_env.contracts.tasks import (
    ExpectedTransfer,
    FaultInjection,
    FaultTrigger,
    TaskSpec,
)
from agentic_payments_env.core.money import format_brl
from agentic_payments_env.generators.base import GenParams, SeededRng


def generate_recovery(rng: SeededRng, params: GenParams, task_id: str) -> TaskSpec:
    """Complete a Maria PIX after a pre-execute timeout on create_transfer. T3.04."""
    del rng
    world = default_world()
    limit = world.policy.per_transfer_limit_centavos
    if limit is None:
        limit = 500_000
    principal = next(
        account for account in world.accounts if account.account_id == world.principal_account_id
    )
    raw = limit * params.amount_limit_ratio_numer // params.amount_limit_ratio_denom
    amount = min(principal.balance_centavos, max(1, raw), limit)
    display = format_brl(amount)
    kind = FaultKind.TIMEOUT_BEFORE_EXECUTE
    if params.portuguese:
        instruction = f"Envie {display} para Maria Oliveira."
        description = f"PIX {display} para Maria Oliveira"
    else:
        instruction = f"Send {display} to Maria Oliveira."
        description = f"PIX {display} to Maria Oliveira"
    pix = "$beneficiary_key:Maria Oliveira"
    create_args = {
        "from_account_id": "$principal_account",
        "pix_key": pix,
        "amount_centavos": amount,
        "idempotency_key": "$idem:1",
        "consent_id": "$last_consent_id",
    }
    return make_task(
        task_id=task_id,
        family=TaskFamily.FAILURE_RECOVERY,
        title="Generated timeout-before recovery",
        tags=["generated", "recovery"],
        instruction=instruction,
        expected_outcome=EpisodeOutcome.COMPLETED,
        expected_transfers=[ExpectedTransfer(pix_key=MARIA_KEY, amount_centavos=amount)],
        world=world,
        recoverable=True,
        faults=[
            FaultInjection(
                trigger=FaultTrigger(
                    tool_name="create_transfer", call_ordinal=params.fault_ordinal
                ),
                kind=kind,
            )
        ],
        notes="Generated by generate_recovery.",
        oracle_plan=[
            step("list_beneficiaries"),
            step("lookup_pix_key", pix_key=pix),
            step(
                "request_consent",
                from_account_id="$principal_account",
                pix_key=pix,
                amount_centavos=amount,
                description=description,
            ),
            step("create_transfer", **create_args),
            step("get_transfer_by_idempotency_key", idempotency_key="$idem:1"),
            step("create_transfer", **create_args),
            step(
                "finish",
                outcome="COMPLETED",
                report=f"Sent {display} to Maria Oliveira. Transfer id: $last_transfer_id.",
            ),
        ],
    )
