"""ROUTINE_TRANSFER parametric generator. M3 T3.02."""

from __future__ import annotations

from agentic_payments_env.benchmark.v0.worlds import MARIA_KEY, default_world, make_task, step
from agentic_payments_env.contracts.common import EpisodeOutcome, TaskFamily
from agentic_payments_env.contracts.tasks import ExpectedTransfer, TaskSpec
from agentic_payments_env.core.money import format_brl
from agentic_payments_env.generators.base import GenParams, SeededRng


def generate_routine(rng: SeededRng, params: GenParams, task_id: str) -> TaskSpec:
    """Build a completed PIX to Maria with int amount from the limit ratio. T3.02."""
    del rng
    world = default_world()
    limit = world.policy.per_transfer_limit_centavos
    if limit is None:
        limit = 500_000
    principal = next(
        account for account in world.accounts if account.account_id == world.principal_account_id
    )
    raw = limit * params.amount_limit_ratio_numer // params.amount_limit_ratio_denom
    amount = min(principal.balance_centavos, max(1, raw))
    amount = min(amount, limit)
    display = format_brl(amount)
    if params.portuguese:
        instruction = f"Envie {display} para Maria Oliveira pela minha conta principal."
        description = f"PIX {display} para Maria Oliveira"
    else:
        instruction = f"Send {display} to Maria Oliveira from my main account."
        description = f"PIX {display} to Maria Oliveira"
    return make_task(
        task_id=task_id,
        family=TaskFamily.ROUTINE_TRANSFER,
        title="Generated routine transfer",
        tags=["generated", "routine"],
        instruction=instruction,
        expected_outcome=EpisodeOutcome.COMPLETED,
        expected_transfers=[ExpectedTransfer(pix_key=MARIA_KEY, amount_centavos=amount)],
        world=world,
        notes="Generated by generate_routine.",
        oracle_plan=[
            step("list_beneficiaries"),
            step("lookup_pix_key", pix_key="$beneficiary_key:Maria Oliveira"),
            step(
                "request_consent",
                from_account_id="$principal_account",
                pix_key="$beneficiary_key:Maria Oliveira",
                amount_centavos=amount,
                description=description,
            ),
            step(
                "create_transfer",
                from_account_id="$principal_account",
                pix_key="$beneficiary_key:Maria Oliveira",
                amount_centavos=amount,
                idempotency_key="$idem:1",
                consent_id="$last_consent_id",
                memo=description,
            ),
            step(
                "finish",
                outcome="COMPLETED",
                report=(
                    f"Sent {display} to Maria Oliveira (MARIA OLIVEIRA SANTOS, Banco Alfa). "
                    "Transfer id: $last_transfer_id."
                ),
            ),
        ],
    )
